### ISSUE TITLE
Error in annotation.R example

### ISSUE THREAD

**Issue by tyluRp** [tidyverse/tidyverse.org#180] opened 2018-07-05 16:21 UTC
I was looking at the [Create and annotation layer](https://ggplot2.tidyverse.org/reference/annotate.html) reference and noticed the following error in the example:

```
#> Error in grid.Call.graphics(C_setviewport, vp, TRUE): non-finite location and/or size for viewport
```

See screenshot:

![screen shot 2018-07-05 at 9 21 17 am](https://user-images.githubusercontent.com/35909636/42335305-cace5c3e-8034-11e8-9143-0ecc5461ce69.png)

**Comment by hadley** [comment] 2018-07-05 16:29
Duplicate of https://github.com/tidyverse/ggplot2/issues/2252

**Closed by hadley** 2018-07-05 16:29 UTC
